aliases:
  - "emojipython"

letters:
  start         :       "a"
  end           :       "z"
  extra         : "öüıçşğÖÜİÇŞĞ"

numbers:
  start         :       "0"
  end           :       "9"

reserved:
  "."           :       "⚫️⚫️"
  ","           :       ","
  "1"           :       "1"
  "2"           :       "2"
  "3"           :       "3"
  "4"           :       "4"
  "5"           :       "5"
  "6"           :       "6"
  "7"           :       "7"
  "8"           :       "8"
  "9"           :       "9"
  "0"           :       "0"
  "🖨️":       "print"
  "➡️❓":      "elif" 
  "❓":        "if"
  "➡️":        "else"
  "🔄":        "while"
  "🔁":        "for"
  "🔍":        "in"
  "⌨️":        "input"
  "⏹️":        "break"
  "⏭️":        "continue"
  "⏩":        "pass"
  "✅":        "True"
  "❌":        "False"
  "🟰":        "is"
  "🏛️":        "class"
  "🔧":        "def"
  "🏁":        "__init__"
  "👤":        "self"
  "↩️":        "return"
  "📜":        "string"
  "🔤":        "str"
  "➕":        "append"
  "➖":        "pop"
  "∧":        "and"
  "∨":        "or"
  "∀":        "all"
  "∃":        "any"
  "∅":        "None"
  "🔢":        "int"