aliases:
  - "pythoniniversèl"
  - "pythonkreyòl"

letters:
  start         :       "a"
  end           :       "z"
  extra         :       "éèàòì"

numbers:
  start         :       "0"
  end           :       "9"

reserved:
  "."           :       "."
  ","           :       ","
  "1"           :       "1"
  "2"           :       "2"
  "3"           :       "3"
  "4"           :       "4"
  "5"           :       "5"
  "6"           :       "6"
  "7"           :       "7"
  "8"           :       "8"
  "9"           :       "9"
  "0"           :       "0"
  "enprime"      :       "print"
  "sinonsi"   :       "elif"
  "si"        :       "if"
  "sinon"       :       "else"
  "pandan"     :       "while"
  "pou"         :       "for"
  "nan"          :       "in"
  "antre"     :       "input"
  "kanpe"   :       "break"
  "kontinye"      :      "continue"
  "pase"      :       "pass"
  "Vrè"        :       "True"
  "Fo"      :       "False"
  "se"         :       "is"
  "klas"      :       "class"
  "def"    :       "def"
  "__init__"  :       "__init__"
  "oto"      :       "self"
  "retounen"      :       "return"
  "chèn":       "string"
  "chn"         :       "str"
  "ajoute"  :       "append"
  "retire"   :       "pop"
  "e"         :       "and"
  "ou"        :       "or"
  "tout"        :       "all"
  "nenpòt"   :       "any"
  "Anyen" :       "None"
  "antye"        :       "int"
