letters:
  start         :       "a"
  end           :       "z"
  extra         : "áéíóúàèëïöüÁÉÍÓÚÀÈËÏÖÜ"

numbers:
  start         :       "0"
  end           :       "9"

reserved:
  "."           :       "."
  ","           :       ","
  "1"           :       "1"
  "2"           :       "2"
  "3"           :       "3"
  "4"           :       "4"
  "5"           :       "5"
  "6"           :       "6"
  "7"           :       "7"
  "8"           :       "8"
  "9"           :       "9"
  "0"           :       "0"
  "uitvoer"     :       "print"
  "andersals"   :       "elif"
  "als"         :       "if"
  "anders"      :       "else"
  "zolang"      :       "while"
  "voor"        :       "for"
  "in"          :       "in"
  "invoer"      :       "input"
  "stop"        :       "break"
  "ga_verder"   :       "continue"
  "sla_over"    :       "pass"
  "waar"        :       "True"
  "onwaar"      :       "False"
  "is"          :       "is"
  "klasse"      :       "class"
  "functie"     :       "def"
  "__begin__"   :       "__init__"
  "zelf"        :       "self"
  "geef_terug"  :       "return"
  "tekst"       :       "string"
  "str"         :       "str"
  "toevoegen"   :       "append"
  "verwijderen" :       "pop"
  "en"          :       "and"
  "of"          :       "or"
  "alle"        :       "all"
  "enig"        :       "any"
  "geen_waarde" :       "None"
  "geheel"      :       "int"
