aliases:
  - "پنجابائپایتھان"
  - "شاہمکھیپایتھان"

letters:
  start         :       "ا"
  end           :       "ی"
  extra         :       "آأؤإءئےݨ"

numbers:
  start         :       "۰"
  end           :       "۹"

reserved:
  "۔"           :       "."
  "،"           :       ","
  "۱"           :       "1"
  "۲"           :       "2"
  "۳"           :       "3"
  "۴"           :       "4"
  "۵"           :       "5"
  "۶"           :       "6"
  "۷"           :       "7"
  "۸"           :       "8"
  "۹"           :       "9"
  "۰"           :       "0"
  "جے"          :       "if"
  "نہیں_تے"     :       "else"
  "جے_نہیں_تے"  :       "elif"
  "لئی"         :       "for"
  "جد_تک"       :       "while"
  "وچ"          :       "in"
  "توڑو"        :       "break"
  "جاری"        :       "continue"
  "لنگھو"       :       "pass"
  "بناؤ"        :       "def"
  "جماعت"       :       "class"
  "واپس"        :       "return"
  "منگواؤ"      :       "import"
  "توں"         :       "from"
  "ویکھو"       :       "as"
  "عوامی"       :       "global"
  "پچھان"       :       "lambda"
  "سچ"          :       "True"
  "جھوٹ"        :       "False"
  "کجھ_نہیں"    :       "None"
  "تے"          :       "and"
  "یا"          :       "or"
  "نہ"          :       "not"
  "ہے"          :       "is"
  "چھاپو"       :       "print"
  "لیو"         :       "input"
  "لمبائی"      :       "len"
  "پینڈا"       :       "range"
  "قسم"         :       "type"
  "کھولو"       :       "open"
  "اکھر"        :       "str"
  "عدد"         :       "int"
  "اشاریہ"      :       "float"
  "لسٹ"         :       "list"
  "لغت"         :       "dict"
  "ٹوکڑی"       :       "set"
  "کوشش"        :       "try"
  "چھڈ_کے"      :       "except"
  "آخرکار"      :       "finally"
  "چکو"         :       "raise"
  "خرابی"       :       "Exception"
  "قیمت_دی_غلطی":       "ValueError"
  "قسم_دی_غلطی" :       "TypeError"
  "نمبر_دی_غلطی":       "IndexError"
