letters:
  start         :       "ا"
  end           :       "ی"

numbers:
  start         :       "۰"
  end           :       "۹"

reserved:
  "۔"           :       "."
  "،"           :       ","
  "۱"           :       "1"
  "۲"           :       "2"
  "۳"           :       "3"
  "۴"           :       "4"
  "۵"           :       "5"
  "۶"           :       "6"
  "۷"           :       "7"
  "۸"           :       "8"
  "۹"           :       "9"
  "۰"           :       "0"
  "وَن"           :       "print"
"تیلگر"         :       "elif"
"ییٚلہِ"        :       "if"
"تیٚلہِ"        :       "else"
"یوتنِت"        :       "while"
"کَر"           :       "for"
"میز"           :       "in"
"اَتھُن"        :       "input"
"فُٹراو"        :       "break"
"برونٛتھ"       :       "continue"
"ترٛاو"         :       "pass"
"پوز"           :       "True"
"اَپوز"         :       "False"
"چھُ"           :       "is"
"کلاس"          :       "class"
"وضاحت"         :       "def"
"__آغاز__"      :       "__init__"
"بہٕ"           :       "self"
"واپس"          :       "return"
"پنے"           :       "string"
"پن"            :       "str"
"مِلاو"         :       "append"
"کَر"           :       "pop"
"بیٚی"          :       "and"
"یا"            :       "or"
"سٲری"          :       "all"
"کَتھی"         :       "any"
"کہنا"          :       "None"
"شُمار"         :       "int"
"__اہم__"       :       "__main__"
