name: Prerelease (main → TestPyPI)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  prerelease:
    runs-on: ubuntu-latest
    environment: test-pypi-universalpython

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine python-semantic-release
          pip install -r utils/requirements.txt

      - name: Determine and tag prerelease version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version --prerelease --prerelease-token b --commit --tag
          semantic-release changelog --commit
          git push && git push --tags

      - name: Build package
        run: bash utils/build_package.sh

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
