name: Publish to Test PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Publish to Test PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for Trusted Publisher authentication

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true